import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers';
import TopNavWrapper from '@/components/navbar/TopNavWrapper';

export const metadata: Metadata = {
  title: 'NextMatch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNavWrapper />
          <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
